//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuralNetwork.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuralNetwork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 509,-0.888206,-0.981816,-0.728466,-0.587542,-1.497451,0.347948,0.535184,0.656251,0.656251,1.528653,9.125519,-0.328221
        ///510,-1.345924,-0.925518,-1.144902,-1.080509,-1.222428,-0.029083,-0.911613,0.782537,0.782537,0.691538,4.403305,-0.158538
        ///511,-0.830991,-1.150710,-1.025921,-1.221357,-0.947404,-0.406114,0.121813,1.413969,1.413969,0.392568,7.157209,-0.268012
        ///512,-1.345924,-0.925518,-1.501848,-1.291781,-0.855729,0.159432,0.397394,0.593108,0.593108,1.648241,7.729689,-0.290514
        ///513,0.656592,0.707129,1.056260,1. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AA1_testset {
            get {
                return ResourceManager.GetString("AA1_testset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,0.656592,0.594533,1.353715,2.018140,0.977762,-0.029083,-0.704928,-0.922329,-0.922329,-0.683723,23.732121,5.593184
        ///2,0.942666,1.270111,1.472697,1.243478,0.061016,-0.688887,-1.256089,-1.301188,-1.301188,-0.743517,23.821138,8.035274
        ///3,-0.888206,-0.869219,-1.025921,-1.432628,-0.397357,-0.217599,0.190708,1.287683,1.287683,0.631744,11.261125,-0.377603
        ///4,-0.830991,-0.531430,-0.490503,-0.446694,0.152691,1.573298,1.706401,1.161396,1.161396,0.512156,16.455641,-0.517426
        ///5,2.029746,1.270111,0.401861,0.327968,-0.5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AA1_trainset {
            get {
                return ResourceManager.GetString("AA1_trainset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 1 1 1 1 1
        ///1 1 1 1 1 1 2
        ///1 1 1 1 1 2 1
        ///1 1 1 1 1 2 2
        ///1 1 1 1 1 3 1
        ///1 1 1 1 1 3 2
        ///1 1 1 1 1 4 1
        ///1 1 1 1 1 4 2
        ///1 1 1 1 2 1 1
        ///1 1 1 1 2 1 2
        ///1 1 1 1 2 2 1
        ///1 1 1 1 2 2 2
        ///1 1 1 1 2 3 1
        ///1 1 1 1 2 3 2
        ///1 1 1 1 2 4 1
        ///1 1 1 1 2 4 2
        ///1 1 1 1 3 1 1
        ///1 1 1 1 3 1 2
        ///1 1 1 1 3 2 1
        ///1 1 1 1 3 2 2
        ///1 1 1 1 3 3 1
        ///1 1 1 1 3 3 2
        ///1 1 1 1 3 4 1
        ///1 1 1 1 3 4 2
        ///1 1 1 2 1 1 1
        ///1 1 1 2 1 1 2
        ///1 1 1 2 1 2 1
        ///1 1 1 2 1 2 2
        ///1 1 1 2 1 3 1
        ///1 1 1 2 1 3 2
        ///1 1 1 2 1 4 1
        ///1 1 1 2 1 4 2
        ///1 1 1 2 2 1 1
        ///1 1 1 2 2 1 2
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_1_test {
            get {
                return ResourceManager.GetString("monks_1_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 1 1 1 3 1
        ///1 1 1 1 3 2 1
        ///1 1 1 1 1 3 2
        ///1 1 1 1 3 3 2
        ///1 1 1 2 1 2 1
        ///1 1 1 2 1 2 2
        ///1 1 1 2 2 3 1
        ///1 1 1 2 2 4 1
        ///1 1 1 2 3 1 2
        ///1 1 2 1 1 1 2
        ///0 1 2 1 1 2 1
        ///0 1 2 1 1 3 1
        ///0 1 2 1 1 4 2
        ///1 1 2 1 2 1 1
        ///0 1 2 1 2 3 1
        ///0 1 2 1 2 3 2
        ///0 1 2 1 2 4 2
        ///0 1 2 1 3 2 1
        ///0 1 2 1 3 4 2
        ///0 1 2 2 1 2 2
        ///0 1 2 2 2 3 2
        ///0 1 2 2 2 4 1
        ///0 1 2 2 2 4 2
        ///0 1 2 2 3 2 2
        ///0 1 2 2 3 3 1
        ///0 1 2 2 3 3 2
        ///0 1 3 1 1 2 1
        ///0 1 3 1 1 4 1
        ///0 1 3 1 2 2 1
        ///0 1 3 1 2 4 1
        ///1 1 3 1 3 1 2
        ///0 1 3 1 3 2 2
        ///0 1 3 1 3 3 1
        ///0 1 3 1 3 4 1
        ///0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_1_train {
            get {
                return ResourceManager.GetString("monks_1_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 1 1 1 1 1
        ///0 1 1 1 1 1 2
        ///0 1 1 1 1 2 1
        ///0 1 1 1 1 2 2
        ///0 1 1 1 1 3 1
        ///0 1 1 1 1 3 2
        ///0 1 1 1 1 4 1
        ///0 1 1 1 1 4 2
        ///0 1 1 1 2 1 1
        ///0 1 1 1 2 1 2
        ///0 1 1 1 2 2 1
        ///0 1 1 1 2 2 2
        ///0 1 1 1 2 3 1
        ///0 1 1 1 2 3 2
        ///0 1 1 1 2 4 1
        ///0 1 1 1 2 4 2
        ///0 1 1 1 3 1 1
        ///0 1 1 1 3 1 2
        ///0 1 1 1 3 2 1
        ///0 1 1 1 3 2 2
        ///0 1 1 1 3 3 1
        ///0 1 1 1 3 3 2
        ///0 1 1 1 3 4 1
        ///0 1 1 1 3 4 2
        ///0 1 1 2 1 1 1
        ///0 1 1 2 1 1 2
        ///0 1 1 2 1 2 1
        ///0 1 1 2 1 2 2
        ///0 1 1 2 1 3 1
        ///0 1 1 2 1 3 2
        ///0 1 1 2 1 4 1
        ///0 1 1 2 1 4 2
        ///0 1 1 2 2 1 1
        ///0 1 1 2 2 1 2
        ///0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_2_test {
            get {
                return ResourceManager.GetString("monks_2_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 1 1 1 2 2
        ///0 1 1 1 1 4 1
        ///0 1 1 1 2 1 1
        ///0 1 1 1 2 1 2
        ///0 1 1 1 2 2 1
        ///0 1 1 1 2 3 1
        ///0 1 1 1 2 4 1
        ///0 1 1 1 3 2 1
        ///0 1 1 1 3 4 1
        ///0 1 1 2 1 1 1
        ///0 1 1 2 1 1 2
        ///0 1 1 2 2 3 1
        ///0 1 1 2 2 4 1
        ///1 1 1 2 2 4 2
        ///0 1 1 2 3 1 2
        ///1 1 1 2 3 2 2
        ///0 1 2 1 1 1 2
        ///0 1 2 1 2 1 2
        ///1 1 2 1 2 2 2
        ///0 1 2 1 2 3 1
        ///1 1 2 1 2 3 2
        ///0 1 2 1 2 4 1
        ///0 1 2 1 3 1 1
        ///0 1 2 1 3 1 2
        ///1 1 2 1 3 2 2
        ///0 1 2 1 3 3 1
        ///1 1 2 1 3 3 2
        ///0 1 2 1 3 4 1
        ///1 1 2 1 3 4 2
        ///0 1 2 2 1 2 1
        ///0 1 2 2 1 4 1
        ///1 1 2 2 2 3 1
        ///1 1 2 2 2 4 1
        ///0 1 2 2 3 1 1
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_2_train {
            get {
                return ResourceManager.GetString("monks_2_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 1 1 1 1 1
        ///1 1 1 1 1 1 2
        ///1 1 1 1 1 2 1
        ///1 1 1 1 1 2 2
        ///1 1 1 1 1 3 1
        ///1 1 1 1 1 3 2
        ///0 1 1 1 1 4 1
        ///0 1 1 1 1 4 2
        ///1 1 1 1 2 1 1
        ///1 1 1 1 2 1 2
        ///1 1 1 1 2 2 1
        ///1 1 1 1 2 2 2
        ///1 1 1 1 2 3 1
        ///1 1 1 1 2 3 2
        ///0 1 1 1 2 4 1
        ///0 1 1 1 2 4 2
        ///1 1 1 1 3 1 1
        ///1 1 1 1 3 1 2
        ///1 1 1 1 3 2 1
        ///1 1 1 1 3 2 2
        ///1 1 1 1 3 3 1
        ///1 1 1 1 3 3 2
        ///0 1 1 1 3 4 1
        ///0 1 1 1 3 4 2
        ///1 1 1 2 1 1 1
        ///1 1 1 2 1 1 2
        ///1 1 1 2 1 2 1
        ///1 1 1 2 1 2 2
        ///1 1 1 2 1 3 1
        ///1 1 1 2 1 3 2
        ///0 1 1 2 1 4 1
        ///0 1 1 2 1 4 2
        ///1 1 1 2 2 1 1
        ///1 1 1 2 2 1 2
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_3_test {
            get {
                return ResourceManager.GetString("monks_3_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 1 1 1 1 2
        ///1 1 1 1 1 2 1
        ///1 1 1 1 1 2 2
        ///0 1 1 1 1 3 1
        ///0 1 1 1 1 4 1
        ///1 1 1 1 2 1 1
        ///1 1 1 1 2 2 2
        ///0 1 1 1 2 4 2
        ///1 1 1 2 1 2 2
        ///0 1 1 2 1 4 2
        ///1 1 1 2 2 2 2
        ///0 1 1 2 2 4 1
        ///0 1 1 2 2 4 2
        ///1 1 1 2 3 1 1
        ///1 1 1 2 3 1 2
        ///1 1 1 2 3 3 1
        ///1 1 1 2 3 3 2
        ///1 1 2 1 1 3 1
        ///1 1 2 1 2 2 1
        ///1 1 2 1 2 2 2
        ///0 1 2 1 2 3 1
        ///1 1 2 1 3 1 1
        ///1 1 2 1 3 1 2
        ///1 1 2 1 3 2 1
        ///1 1 2 1 3 2 2
        ///1 1 2 1 3 3 2
        ///0 1 2 1 3 4 1
        ///1 1 2 2 1 3 1
        ///0 1 2 2 1 4 2
        ///1 1 2 2 2 1 1
        ///1 1 2 2 2 2 1
        ///1 1 2 2 2 2 2
        ///1 1 2 2 3 1 1
        ///1 1 2 2 3 2 1
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_3_train {
            get {
                return ResourceManager.GetString("monks_3_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00,0.00
        ///0.10,0.01
        ///0.20,0.02
        ///0.30,0.03
        ///0.40,0.04
        ///0.50,0.05
        ///0.60,0.07
        ///0.70,0.08
        ///0.80,0.09
        ///0.90,0.10
        ///1.00,0.11
        ///1.10,0.12
        ///1.20,0.13
        ///1.30,0.14
        ///1.40,0.15
        ///1.50,0.16
        ///1.60,0.17
        ///1.70,0.19
        ///1.80,0.20
        ///1.90,0.21
        ///2.00,0.22
        ///2.10,0.23
        ///2.20,0.24
        ///2.30,0.25
        ///2.40,0.26
        ///2.50,0.27
        ///2.60,0.28
        ///2.70,0.29
        ///2.80,0.30
        ///2.90,0.31
        ///3.00,0.32
        ///3.10,0.33
        ///3.20,0.34
        ///3.30,0.35
        ///3.40,0.36
        ///3.50,0.37
        ///3.60,0.38
        ///3.70,0.39
        ///3.80,0.40
        ///3.90,0.41
        ///4.00,0.42
        ///4.10,0.43
        ///4.20,0.44
        ///4.30,0.45
        ///4.40,0.46
        ///4.50,0.47
        ///4.60,0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sinData {
            get {
                return ResourceManager.GetString("sinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.00,-1.00
        ///100.10,-1.00
        ///100.20,-1.00
        ///100.30,-1.00
        ///100.40,-1.00
        ///100.50,-1.00
        ///100.60,-1.00
        ///100.70,-1.00
        ///100.80,-1.00
        ///100.90,-1.00
        ///101.00,-1.00
        ///101.10,-1.00
        ///101.20,-0.99
        ///101.30,-0.99
        ///101.40,-0.99
        ///101.50,-0.99
        ///101.60,-0.99
        ///101.70,-0.99
        ///101.80,-0.99
        ///101.90,-0.98
        ///102.00,-0.98
        ///102.10,-0.98
        ///102.20,-0.98
        ///102.30,-0.98
        ///102.40,-0.97
        ///102.50,-0.97
        ///102.60,-0.97
        ///102.70,-0.96
        ///102.80,-0.96
        ///102.90,-0.96
        ///103.00,-0.96
        ///103.10,-0.95
        ///103.20,-0.95
        ///103.30,-0.95
        ///103.40,-0.94
        ///103.50,-0.94
        ///103.60,- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sinTest {
            get {
                return ResourceManager.GetString("sinTest", resourceCulture);
            }
        }
    }
}
