//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuralNetwork.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuralNetwork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 509,-0.888206,-0.981816,-0.728466,-0.587542,-1.497451,0.347948,0.535184,0.656251,0.656251,1.528653,9.125519,-0.328221
        ///510,-1.345924,-0.925518,-1.144902,-1.080509,-1.222428,-0.029083,-0.911613,0.782537,0.782537,0.691538,4.403305,-0.158538
        ///511,-0.830991,-1.150710,-1.025921,-1.221357,-0.947404,-0.406114,0.121813,1.413969,1.413969,0.392568,7.157209,-0.268012
        ///512,-1.345924,-0.925518,-1.501848,-1.291781,-0.855729,0.159432,0.397394,0.593108,0.593108,1.648241,7.729689,-0.290514
        ///513,0.656592,0.707129,1.056260,1. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AA1_testset {
            get {
                return ResourceManager.GetString("AA1_testset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,0.656592,0.594533,1.353715,2.018140,0.977762,-0.029083,-0.704928,-0.922329,-0.922329,-0.683723,23.732121,5.593184
        ///2,0.942666,1.270111,1.472697,1.243478,0.061016,-0.688887,-1.256089,-1.301188,-1.301188,-0.743517,23.821138,8.035274
        ///3,-0.888206,-0.869219,-1.025921,-1.432628,-0.397357,-0.217599,0.190708,1.287683,1.287683,0.631744,11.261125,-0.377603
        ///4,-0.830991,-0.531430,-0.490503,-0.446694,0.152691,1.573298,1.706401,1.161396,1.161396,0.512156,16.455641,-0.517426
        ///5,2.029746,1.270111,0.401861,0.327968,-0.5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AA1_trainset {
            get {
                return ResourceManager.GetString("AA1_trainset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 1 1 1 1 1
        ///1 1 1 1 1 1 2
        ///1 1 1 1 1 2 1
        ///1 1 1 1 1 2 2
        ///1 1 1 1 1 3 1
        ///1 1 1 1 1 3 2
        ///1 1 1 1 1 4 1
        ///1 1 1 1 1 4 2
        ///1 1 1 1 2 1 1
        ///1 1 1 1 2 1 2
        ///1 1 1 1 2 2 1
        ///1 1 1 1 2 2 2
        ///1 1 1 1 2 3 1
        ///1 1 1 1 2 3 2
        ///1 1 1 1 2 4 1
        ///1 1 1 1 2 4 2
        ///1 1 1 1 3 1 1
        ///1 1 1 1 3 1 2
        ///1 1 1 1 3 2 1
        ///1 1 1 1 3 2 2
        ///1 1 1 1 3 3 1
        ///1 1 1 1 3 3 2
        ///1 1 1 1 3 4 1
        ///1 1 1 1 3 4 2
        ///1 1 1 2 1 1 1
        ///1 1 1 2 1 1 2
        ///1 1 1 2 1 2 1
        ///1 1 1 2 1 2 2
        ///1 1 1 2 1 3 1
        ///1 1 1 2 1 3 2
        ///1 1 1 2 1 4 1
        ///1 1 1 2 1 4 2
        ///1 1 1 2 2 1 1
        ///1 1 1 2 2 1 2
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_1_test {
            get {
                return ResourceManager.GetString("monks_1_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 1 1 1 3 1
        ///1 1 1 1 3 2 1
        ///1 1 1 1 1 3 2
        ///1 1 1 1 3 3 2
        ///1 1 1 2 1 2 1
        ///1 1 1 2 1 2 2
        ///1 1 1 2 2 3 1
        ///1 1 1 2 2 4 1
        ///1 1 1 2 3 1 2
        ///1 1 2 1 1 1 2
        ///0 1 2 1 1 2 1
        ///0 1 2 1 1 3 1
        ///0 1 2 1 1 4 2
        ///1 1 2 1 2 1 1
        ///0 1 2 1 2 3 1
        ///0 1 2 1 2 3 2
        ///0 1 2 1 2 4 2
        ///0 1 2 1 3 2 1
        ///0 1 2 1 3 4 2
        ///0 1 2 2 1 2 2
        ///0 1 2 2 2 3 2
        ///0 1 2 2 2 4 1
        ///0 1 2 2 2 4 2
        ///0 1 2 2 3 2 2
        ///0 1 2 2 3 3 1
        ///0 1 2 2 3 3 2
        ///0 1 3 1 1 2 1
        ///0 1 3 1 1 4 1
        ///0 1 3 1 2 2 1
        ///0 1 3 1 2 4 1
        ///1 1 3 1 3 1 2
        ///0 1 3 1 3 2 2
        ///0 1 3 1 3 3 1
        ///0 1 3 1 3 4 1
        ///0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_1_train {
            get {
                return ResourceManager.GetString("monks_1_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 1 1 1 1 1
        ///0 1 1 1 1 1 2
        ///0 1 1 1 1 2 1
        ///0 1 1 1 1 2 2
        ///0 1 1 1 1 3 1
        ///0 1 1 1 1 3 2
        ///0 1 1 1 1 4 1
        ///0 1 1 1 1 4 2
        ///0 1 1 1 2 1 1
        ///0 1 1 1 2 1 2
        ///0 1 1 1 2 2 1
        ///0 1 1 1 2 2 2
        ///0 1 1 1 2 3 1
        ///0 1 1 1 2 3 2
        ///0 1 1 1 2 4 1
        ///0 1 1 1 2 4 2
        ///0 1 1 1 3 1 1
        ///0 1 1 1 3 1 2
        ///0 1 1 1 3 2 1
        ///0 1 1 1 3 2 2
        ///0 1 1 1 3 3 1
        ///0 1 1 1 3 3 2
        ///0 1 1 1 3 4 1
        ///0 1 1 1 3 4 2
        ///0 1 1 2 1 1 1
        ///0 1 1 2 1 1 2
        ///0 1 1 2 1 2 1
        ///0 1 1 2 1 2 2
        ///0 1 1 2 1 3 1
        ///0 1 1 2 1 3 2
        ///0 1 1 2 1 4 1
        ///0 1 1 2 1 4 2
        ///0 1 1 2 2 1 1
        ///0 1 1 2 2 1 2
        ///0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_2_test {
            get {
                return ResourceManager.GetString("monks_2_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 1 1 1 1 2 2
        ///0 1 1 1 1 4 1
        ///0 1 1 1 2 1 1
        ///0 1 1 1 2 1 2
        ///0 1 1 1 2 2 1
        ///0 1 1 1 2 3 1
        ///0 1 1 1 2 4 1
        ///0 1 1 1 3 2 1
        ///0 1 1 1 3 4 1
        ///0 1 1 2 1 1 1
        ///0 1 1 2 1 1 2
        ///0 1 1 2 2 3 1
        ///0 1 1 2 2 4 1
        ///1 1 1 2 2 4 2
        ///0 1 1 2 3 1 2
        ///1 1 1 2 3 2 2
        ///0 1 2 1 1 1 2
        ///0 1 2 1 2 1 2
        ///1 1 2 1 2 2 2
        ///0 1 2 1 2 3 1
        ///1 1 2 1 2 3 2
        ///0 1 2 1 2 4 1
        ///0 1 2 1 3 1 1
        ///0 1 2 1 3 1 2
        ///1 1 2 1 3 2 2
        ///0 1 2 1 3 3 1
        ///1 1 2 1 3 3 2
        ///0 1 2 1 3 4 1
        ///1 1 2 1 3 4 2
        ///0 1 2 2 1 2 1
        ///0 1 2 2 1 4 1
        ///1 1 2 2 2 3 1
        ///1 1 2 2 2 4 1
        ///0 1 2 2 3 1 1
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_2_train {
            get {
                return ResourceManager.GetString("monks_2_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 1 1 1 1 1
        ///1 1 1 1 1 1 2
        ///1 1 1 1 1 2 1
        ///1 1 1 1 1 2 2
        ///1 1 1 1 1 3 1
        ///1 1 1 1 1 3 2
        ///0 1 1 1 1 4 1
        ///0 1 1 1 1 4 2
        ///1 1 1 1 2 1 1
        ///1 1 1 1 2 1 2
        ///1 1 1 1 2 2 1
        ///1 1 1 1 2 2 2
        ///1 1 1 1 2 3 1
        ///1 1 1 1 2 3 2
        ///0 1 1 1 2 4 1
        ///0 1 1 1 2 4 2
        ///1 1 1 1 3 1 1
        ///1 1 1 1 3 1 2
        ///1 1 1 1 3 2 1
        ///1 1 1 1 3 2 2
        ///1 1 1 1 3 3 1
        ///1 1 1 1 3 3 2
        ///0 1 1 1 3 4 1
        ///0 1 1 1 3 4 2
        ///1 1 1 2 1 1 1
        ///1 1 1 2 1 1 2
        ///1 1 1 2 1 2 1
        ///1 1 1 2 1 2 2
        ///1 1 1 2 1 3 1
        ///1 1 1 2 1 3 2
        ///0 1 1 2 1 4 1
        ///0 1 1 2 1 4 2
        ///1 1 1 2 2 1 1
        ///1 1 1 2 2 1 2
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_3_test {
            get {
                return ResourceManager.GetString("monks_3_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1 1 1 1 1 2
        ///1 1 1 1 1 2 1
        ///1 1 1 1 1 2 2
        ///0 1 1 1 1 3 1
        ///0 1 1 1 1 4 1
        ///1 1 1 1 2 1 1
        ///1 1 1 1 2 2 2
        ///0 1 1 1 2 4 2
        ///1 1 1 2 1 2 2
        ///0 1 1 2 1 4 2
        ///1 1 1 2 2 2 2
        ///0 1 1 2 2 4 1
        ///0 1 1 2 2 4 2
        ///1 1 1 2 3 1 1
        ///1 1 1 2 3 1 2
        ///1 1 1 2 3 3 1
        ///1 1 1 2 3 3 2
        ///1 1 2 1 1 3 1
        ///1 1 2 1 2 2 1
        ///1 1 2 1 2 2 2
        ///0 1 2 1 2 3 1
        ///1 1 2 1 3 1 1
        ///1 1 2 1 3 1 2
        ///1 1 2 1 3 2 1
        ///1 1 2 1 3 2 2
        ///1 1 2 1 3 3 2
        ///0 1 2 1 3 4 1
        ///1 1 2 2 1 3 1
        ///0 1 2 2 1 4 2
        ///1 1 2 2 2 1 1
        ///1 1 2 2 2 2 1
        ///1 1 2 2 2 2 2
        ///1 1 2 2 3 1 1
        ///1 1 2 2 3 2 1
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monks_3_train {
            get {
                return ResourceManager.GetString("monks_3_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.2529,-0.33517,1
        ///0.83165,0.86605,1
        ///3.202,4.0682,1
        ///1.3393,1.8007,1
        ///2.3276,4.0135,1
        ///3.5081,3.9491,1
        ///1.1111,1.6074,1
        ///1.0407,2.2386,1
        ///1.5073,1.0305,1
        ///2.4411,4.2413,1
        ///1.7952,3.2846,1
        ///1.0222,0.76934,1
        ///0.42705,-0.66236,1
        ///1.6297,2.8197,1
        ///1.7789,3.3683,1
        ///1.4648,2.6986,1
        ///1.738,3.2677,1
        ///0.90459,0.33313,1
        ///2.5492,4.3295,1
        ///-0.17462,-0.76423,1
        ///2.1446,2.7308,1
        ///2.669,2.6561,1
        ///1.1512,2.6796,1
        ///1.9429,3.066,1
        ///2.2918,4.3068,1
        ///1.3854,3.3866,1
        ///1.9864,1.9947,1
        ///2.4121,4.175,1
        ///1.0629,1.5832,1
        ///2.8352,5.0445,1
        ///3.0945,5.6011,1
        ///2.3212 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string test_gaussian {
            get {
                return ResourceManager.GetString("test_gaussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.8886,4.0802,1
        ///1.2352,2.1141,1
        ///0.59773,1.2429,1
        ///0.57762,0.061066,1
        ///2.4882,3.5792,1
        ///1.8226,0.88749,1
        ///1.8039,3.6978,1
        ///3.4193,4.5842,1
        ///2.2916,2.3948,1
        ///2.1978,3.0768,1
        ///3.5877,4.1443,1
        ///1.1955,1.7752,1
        ///2.6966,3.5594,1
        ///2.8351,6.1386,1
        ///1.7563,3.6204,1
        ///2.2157,1.1611,1
        ///0.83416,1.6334,1
        ///0.85205,0.067248,1
        ///2.1049,2.9364,1
        ///2.7223,4.2258,1
        ///4.5855,7.5258,1
        ///1.3331,1.7632,1
        ///2.1873,4.6461,1
        ///1.9175,2.4598,1
        ///0.066977,0.3841,1
        ///1.561,2.9172,1
        ///0.20532,0.38176,1
        ///2.8404,5.0235,1
        ///1.112,1.9479,1
        ///2.1001,2.471,1
        ///1.4555,0.61971,1
        ///2.303 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string train_gaussian {
            get {
                return ResourceManager.GetString("train_gaussian", resourceCulture);
            }
        }
    }
}
